[package]
name = "rf-ecs"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "RustForge Archetype ECS：World/Query/调度器/事件/命令/层级"

[dependencies]
rf-core = { workspace = true }
rf-math = { workspace = true }
rf-task = { workspace = true }
