[package]
name = "rf-distribute"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "RustForge 分发：构建/打包/签名/商店/更新/成就/云存档/合规/SDK"

[dependencies]
rf-core = { workspace = true }
rf-asset = { workspace = true }
flate2 = "1"
serde_json = "1"
